import type { Viewport } from 'next'

import '@/styles/globals.css'

import Header from '@/app/_components/header'
import { DEFAULT_TITLE } from '@/lib/common'

export const metadata = {
  manifest: '/manifest.json',
  description: 'Generated by create-t3-app',
  icons: {
    icon: '/favicon.png',
    shortcut: '/favicon.png',
    apple: '/icon.png',
  },
  title: DEFAULT_TITLE,
}

export const viewport: Viewport = {
  themeColor: '#15232d',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <div className='flex min-h-screen flex-col bg-cb-dark-blue text-cb-white'>
          <Header />
          {children}
        </div>
      </body>
    </html>
  )
}
